### ISSUE TITLE
Avoid re-encoding and decoding output from serializer

### ISSUE THREAD

**Issue by MrAwesomeRocks** [dajiaji/pyseto#112]
**Is your feature request related to a problem? Please describe.**
When using a serializer such as [`orjson`](https://github.com/ijl/orjson), a `bytes` object is output by default, but the `serializer` field expects a function that returns a `str`, that is immediately encoded into a bytes object.

**Describe the solution you'd like**
Make it so that serializer can output either a `str` or a `bytes` object. Also, the serializer field should ideally be a function and not a class, since Python functions are objects themselves and can be passed into functions (see `map` and `filter`).

**Describe alternatives you've considered**
Having my serializer return a `str` by doing `orjson.dumps().decode("utf-8")`, but this is inefficient.

**Additional context**
N/A

**Comment by MrAwesomeRocks** [comment]
@dajiaji Would this feature be possible?

**Comment by dajiaji** [comment]
Sorry to keep you waiting.

Possible. At least, re-encoding/decoding Please wait for a while.ait for a while.

**Comment by dajiaji** [comment]
@MrAwesomeRocks  I've released v1.6.5. Please let me know if there are any problems.

**Comment by MrAwesomeRocks** [comment]
Thank you very much! This is a great library, thank you for maintaining and improving it, and for getting back to me so quickly!

**Comment by dajiaji** [comment]
Thanks for reporting the problem too! If you could push the star button I would be very happy :-)

**Comment by MrAwesomeRocks** [comment]
Done!
