### ISSUE TITLE
Token payloads are not decoded when using `local` Keys

### ISSUE THREAD

**Issue by MrAwesomeRocks** [dajiaji/pyseto#113]
**Describe the bug**
When using a `local` Key, the token payload is not decoded, and so [this example](https://pyseto.readthedocs.io/en/stable/paseto_usage.html#using-serializer-deserializer-for-payload-and-footer) does not work for `local` keys. This is due to [these lines](https://github.com/dajiaji/pyseto/blob/a05493444dcdd510f1637b79aa6c61f0f7b859e1/pyseto/paseto.py#L199-L201) in `paseto.py` that cause the function to exit early.

**To Reproduce**
1. Go to this example: https://pyseto.readthedocs.io/en/stable/paseto_usage.html#using-serializer-deserializer-for-payload-and-footer
2. Follow the directions, but use a `local` key.
3. When running `decoded.payload["data"]`, observe the error.

**Expected behavior**
The payload of the decoded token is a dictionary when `deserializer` is passed.

**Comment by dajiaji** [comment]
Thanks for reporting. I'll check it out.

**Comment by dajiaji** [comment]
@MrAwesomeRocks Again, thanks for reporting. I fixed the bug and released v1.6.4.
