### ISSUE TITLE
to_peer_paserk_id for k3.secret

### ISSUE THREAD

**Issue by Eh2406** [dajiaji/pyseto#127]
This is a feature request because `to_peer_paserk_id` is working as documented.
Is there a technical reason why `to_peer_paserk_id` does not work on a V3 secret key?
If Yes, can we add it to the documentation?
If No, can we add support for it?

**Comment by dajiaji** [comment]
Thanks for your report. I just forgot to implement it. Please wait for a while.

**Comment by dajiaji** [comment]
@Eh2406 I've fixed this bug and released v1.6.6. Could you try the latest version?

**Comment by Eh2406** [comment]
That works well! Thank you!
Does it make sense to add a more general way to get the public key from a secret key?
So that the `to_peer_paserk_id` is a short hand for `to_peer_key().to_paserk_id()`.

**Comment by dajiaji** [comment]
Yes, it does. It's good idea. Thanks.

I should have named "to_public_paserk_id()" instead of "to_peer_paserk_id()" so "to_public_key()" (or "public_key()") might be useful. I will try to find time to implement it.
