### ISSUE TITLE
Typo in the Documentation

### ISSUE THREAD

**Issue by stsch9** [dajiaji/pyseto#182]
I think in

https://pyseto.readthedocs.io/en/latest/paseto_usage.html#v4-local

it must be **"Symmetric Authenticated Encryption with XChaCha20 + BLAKE2b-MAC  (Encrypt-then-MAC)"** instead of **"Symmetric Authenticated Encryption with AES-256-CTR + HMAC-SHA384 (Encrypt-then-MAC)"**

**Comment by dajiaji** [comment]
Thanks for the report!

I will fix it soon.

**Comment by dajiaji** [comment]
https://github.com/dajiaji/pyseto/pull/183
