### ISSUE TITLE
passlib alternative ?

### ISSUE THREAD

**Issue by omars44** [dajiaji/pyseto#314]
**Is your feature request related to a problem? Please describe.**
There is a minor issue as of now, but it encompasses potential issues, passlib is not in active development (last commit 2 years ago)

on the practical side of things, I have deprecation warnings like this one
```
.venv/lib/python3.11/site-packages/passlib/utils/__init__.py:854: DeprecationWarning: 'crypt' is deprecated and slated for removal in Python 3.13
    from crypt import crypt as _crypt
```

**Describe the solution you'd like**
I am willing to help with this issue, I haven't done the research needed for a replacement or a fork yet. I just wanted to raise a flag and see from there.

Ideas are welcome :)

**Describe alternatives you've considered**
- TBD

**Additional context**
passlib-src: https://foss.heptapod.net/python-libs/passlib

pypi: https://pypi.org/project/passlib/1.7.4/#history

**Comment by dmgawel** [comment]
It looks like passlib is used only for argon2 hashing ([ref](https://github.com/dajiaji/pyseto/blob/9528b7b3994789cde1817d59530281fa9cdba2eb/pyseto/key_sodium.py#L21)). Maybe it could be replaced by [argon2-cffi](https://github.com/hynek/argon2-cffi)?

**Comment by dmgawel** [comment]
argon2-cffi is used by passlib internally, so the transition was fairly simple, PR raised: https://github.com/dajiaji/pyseto/pull/315
