### ISSUE TITLE
Upgrade `cryptography` dependency to 44.x

### ISSUE THREAD

**Issue by PrieJos** [dajiaji/pyseto#434]
**Describe the bug**
Python dependency `cryptography` released yesterday version [44.0.0](https://github.com/pyca/cryptography/releases/tag/44.0.0). Since then, we are having a dependency conflict resolution because `pyseto` requires a `cryptography` version lower than 44.0.0. So, is there any plan to upgrade this dependency? 

**To Reproduce**
Try to update `cryptography` package to the latest (44.0.0) while having `pyseto` also installed on the same virtualenv.

**Expected behavior**
No dependency conflicts while trying to install latest versions of both `cryptography` and `pyseto`.

Thanks,
Jose M. Prieto

**Comment by dajiaji** [comment]
@PrieJos Thank you for filing the issue! I've fixed  and released v1.8.1.

**Comment by PrieJos** [comment]
@dajiaji Thanks so much for the prompt reaction on this.
