### ISSUE TITLE
Support creating keys from bytes

### ISSUE THREAD

**Issue by not-my-profile** [dajiaji/pyseto#62]
Currently `Key` can only be created from Paserk or PEM, which limits the interoperability of Pyseto.

For example: If I want to create a key pair with Rust, and sign a Paseto token with Rust, I cannot then verify it with Pyseto because the Rust libraries only provide the public key as binary, meaning I'd need to convert it to either Paserk or PEM, which is just cumbersome.

Most Paseto libraries allow importing/exporting keys as binary, so it makes sense to support it, to maximize interoperability.

**Comment by dajiaji** [comment]
@not-my-profile `Key` also has another method named `from_asymmetric_key_params`. Is this the method you want?

https://github.com/dajiaji/pyseto/blob/646c9aa2505b7fde1d0e6cb2eb4d1be76564306f/pyseto/key.py#L157

**Comment by not-my-profile** [comment]
No, I am looking for some interoperable string format. I was planning on just using base64 but if Paseto wants libraries to enforce Algorithm Lucidity, I guess I'll have to use Paserk. Thanks, anyway :)

**Comment by dajiaji** [comment]
@not-my-profile FYI: I've implemented a CLI tool for generating PASERK.

https://github.com/dajiaji/mkkey
